spring.application.name=whatsrecovery

spring.jpa.hibernate.ddl-auto=validate

spring.datasource.url=jdbc:postgresql://localhost:5432/whatsrecovery
spring.datasource.username=whatsrecovery
spring.datasource.password=whatsrecovery
